apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yp0pa10cl-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4cae8d87e6.ncwm.p3.openshiftapps.com/rhtap/rhtap-qe:065eb35020468e528e6409c76d59064030a82a73@sha256:16f8e6eb7d82dca6d3393e2d0cefb4cde18817b0495a2b46ddfbc57d4b34e6f2
          name: container-image
